### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible' on django 3.0

### ISSUE THREAD

**Issue by mtellezj** [alsoicode/django-maintenancemode-2#13]
After upgrade to django 3.0 I get an "ImportError: cannot import name 'python_2_unicode_compatible'" error. Django 3.0 no longer support python 2.x.

**Comment by alsoicode** [comment]
@mtellezj Sorry for the delay addressing Django 3 compatibility, but I've released version 1.2.0 to PyPi. Automated and manual testing with Django 3 and Python 3.6.5 are working for me, but if you run into any issues, please let me know.
