### ISSUE TITLE
Django 4.0 support

### ISSUE THREAD

**Issue by bluesurfer** [alsoicode/django-maintenancemode-2#19]
The library is not compatible with Django >= 4.0.0. But it appears to be an easy fix: rename `ugettext_lazy` to `
gettext_lazy` 

Reference https://docs.djangoproject.com/en/4.1/releases/3.0/#id3

**Comment by alsoicode** [comment]
Hello. Pull requests are always welcome. I’m split between multiple projects at home and work and have zero time to work on this.

**Comment by alsoicode** [comment]
@bluesurfer Version 2.0.0 is now available on PyPi: https://pypi.org/project/django-maintenancemode-2/
