### ISSUE TITLE
Django 1.10 patch

### ISSUE THREAD

**Issue by bezkos** [alsoicode/django-maintenancemode-2#2]
I did some modifications to work with django 1.10.
In middleware.py
add
from django import VERSION as DJANGO_VERSION
from django.utils import deprecation
modify
class MaintenanceModeMiddleware(deprecation.MiddlewareMixin if DJANGO_VERSION >= (1, 10, 0) else object):

In defaults.py
modify
return HttpResponseTemporaryUnavailable(loader.render_to_string(template_name, {'request_path': request.path,}))

**Comment by alsoicode** [comment]
Hello, sorry for the slow reply, I've been incredibly busy. If you'd like to create a pull request, I can look at integrating your changes.

**Comment by alsoicode** [comment]
Fixed by: https://github.com/alsoicode/django-maintenancemode-2/pull/3
