### ISSUE TITLE
Version 1.1.6 is not avaliable on PyPi

### ISSUE THREAD

**Issue by yrchen** [alsoicode/django-maintenancemode-2#4]
The latest version on PyPi is v1.1.5 and it's not supported Django 1.10 :(
https://pypi.python.org/pypi/django-maintenancemode-2

**Comment by alsoicode** [comment]
Sorry about that. Pull requests are always welcome if you know what needs to be updated for Django 1.10.

**Comment by yrchen** [comment]
@alsoicode Everything is fine on Django 1.10 from master branch. But it will be more convenient if you can release the new version to PyPi. Thanks.

**Comment by alsoicode** [comment]
@yrchen Gotcha. Unfortunately I won't be able to do that until later this evening, but will get the latest deployed to PyPi asap for you.

**Comment by alsoicode** [comment]
@yrchen v1.1.6 has been tagged and released to PyPi.
