### ISSUE TITLE
Not compatible with Django 2.0

### ISSUE THREAD

**Issue by kakulukia** [alsoicode/django-maintenancemode-2#8]
on_delete is missing here
https://github.com/alsoicode/django-maintenancemode-2/blob/13c8070356445e6ffc2ef5fdcb8c66192f95c2b3/maintenancemode/models.py#L12

I patched this and the migrations, but maintenance Mode is not working so it looks like something else is missing.

**Comment by alsoicode** [comment]
I'll try to take a look today.

**Comment by kakulukia** [comment]
okay, im not getting a maintenance page because of this test:
https://github.com/alsoicode/django-maintenancemode-2/blob/13c8070356445e6ffc2ef5fdcb8c66192f95c2b3/maintenancemode/middleware.py#L29

And after that i was kicked out because i cannot configure the staff to also be affected. (Its necessary for my use case) .. but even after that i got the following error:

unsupported operand type(s) for +: 'map' and 'list'
maintenancemode/middleware.py in process_request, line 50

Id like to request a setting to also be able to kick the staff out in maintenance mode.
At first i tried this other django-maintenance-mode, but i like the admin page for en/disabling the maintenance mode. :)
